package Vistas;

import Controlador.MyTools;
import Controlador.PeliTools;
import Modelo.Film;
import Modelo.Language;
import Modelo.LenguajeCombo;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * @author Andres
 */
public class Ventana_Peliculas extends javax.swing.JFrame {

    JFrame padre;
    MyTools MT;
    PeliTools PT;

    private int PeliActual;
    private boolean nuevoRegistro;

    public Ventana_Peliculas() {
    }

    Ventana_Peliculas(JFrame padre) {
        this.padre = padre;
        initComponents();
        SetUi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrim = new javax.swing.JButton();
        btnAnte = new javax.swing.JButton();
        btnUlti = new javax.swing.JButton();
        btnSigu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPeliActual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPeliTotal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPeliId = new javax.swing.JTextField();
        txtPeliTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbPeliLenguaje = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPeliDescripcion = new javax.swing.JTextArea();
        cmbPeliRating = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPeliDuracion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPeliModificado = new javax.swing.JLabel();
        txtPeliRTime = new javax.swing.JTextField();
        txtPeliRRate = new javax.swing.JTextField();
        txtPeliRCost = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        chTrailers = new javax.swing.JCheckBox();
        chDeleted = new javax.swing.JCheckBox();
        chComentarios = new javax.swing.JCheckBox();
        chBehind = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnReparto = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnPrim.setText("|<");
        btnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimActionPerformed(evt);
            }
        });

        btnAnte.setText("<");
        btnAnte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteActionPerformed(evt);
            }
        });

        btnUlti.setText(">|");
        btnUlti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltiActionPerformed(evt);
            }
        });

        btnSigu.setText(">");
        btnSigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguActionPerformed(evt);
            }
        });

        jLabel1.setText("Pelicula ");

        txtPeliActual.setText("jLabel2");

        jLabel3.setText("de");

        txtPeliTotal.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnPrim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnte)
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPeliActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPeliTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSigu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUlti)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrim)
                    .addComponent(btnAnte)
                    .addComponent(btnUlti)
                    .addComponent(btnSigu)
                    .addComponent(jLabel1)
                    .addComponent(txtPeliActual)
                    .addComponent(jLabel3)
                    .addComponent(txtPeliTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Pelicula ID");

        txtPeliId.setText("jTextField1");
        txtPeliId.setEnabled(false);

        txtPeliTitulo.setText("jTextField1");
        txtPeliTitulo.setEnabled(false);

        jLabel4.setText("Titulo");

        jLabel6.setText("Lenguaje");

        cmbPeliLenguaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeliLenguaje.setEnabled(false);

        jLabel7.setText("Descripcion");

        txtPeliDescripcion.setColumns(20);
        txtPeliDescripcion.setRows(5);
        txtPeliDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(txtPeliDescripcion);

        cmbPeliRating.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeliRating.setEnabled(false);

        jLabel8.setText("Rating");

        jLabel9.setText("Duración");

        txtPeliDuracion.setText("jTextField1");
        txtPeliDuracion.setEnabled(false);

        jLabel10.setText("Tiempo de alquiler:");

        jLabel11.setText("Porcentaje:");

        jLabel12.setText("Coste de cambio:");

        txtPeliModificado.setText("jLabel14");

        txtPeliRTime.setText("jTextField1");
        txtPeliRTime.setEnabled(false);

        txtPeliRRate.setText("jTextField2");
        txtPeliRRate.setEnabled(false);

        txtPeliRCost.setText("jTextField3");
        txtPeliRCost.setEnabled(false);

        chTrailers.setText("Trailers");
        chTrailers.setEnabled(false);

        chDeleted.setText("Deleted Scenes");
        chDeleted.setEnabled(false);

        chComentarios.setText("Commentaries");
        chComentarios.setEnabled(false);

        chBehind.setText("Behind the Scenes");
        chBehind.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(chTrailers)
                        .addGap(18, 18, 18)
                        .addComponent(chComentarios))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(chDeleted)
                        .addGap(18, 18, 18)
                        .addComponent(chBehind)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chTrailers)
                    .addComponent(chComentarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chDeleted)
                    .addComponent(chBehind))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel5.setText("Genero:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPeliId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbPeliLenguaje, 0, 116, Short.MAX_VALUE))
                            .addComponent(txtPeliTitulo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPeliDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbPeliRating, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPeliRCost))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPeliRTime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPeliRRate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPeliModificado, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPeliId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPeliLenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeliTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbPeliRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPeliDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPeliRTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeliRRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPeliRCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeliModificado))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        btnReparto.setText("Reparto");
        btnReparto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepartoActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.setEnabled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReparto, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReparto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimActionPerformed
        mostrarDatos(1);
    }//GEN-LAST:event_btnPrimActionPerformed

    private void btnAnteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteActionPerformed
        mostrarDatos(PeliActual - 1);
    }//GEN-LAST:event_btnAnteActionPerformed

    private void btnSiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguActionPerformed
        mostrarDatos(PeliActual + 1);
    }//GEN-LAST:event_btnSiguActionPerformed

    private void btnUltiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltiActionPerformed
        mostrarDatos(PT.ContarPelis());
    }//GEN-LAST:event_btnUltiActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        habilitarEdicion(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        habilitarEdicion(false);
        mostrarDatos(PeliActual);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevoRegistro = true;
        habilitarEdicion(true);
        int ct = PT.ContarPelis() + 1;

        txtPeliId.setText("" + ct);
        txtPeliTitulo.setText("");
        txtPeliDescripcion.setText("");
        txtPeliDuracion.setText("");
        txtPeliRCost.setText("");
        txtPeliRRate.setText("");
        txtPeliRTime.setText("");
        txtPeliModificado.setText("");
        cmbPeliLenguaje.setSelectedIndex(-1);
        cmbPeliRating.setSelectedIndex(-1);
        txtPeliActual.setText("pendiente");
        txtPeliTotal.setText("guardar.");
        chBehind.setSelected(false);
        chComentarios.setSelected(false);
        chDeleted.setSelected(false);
        chTrailers.setSelected(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRepartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepartoActionPerformed
        Dialogo_Lista reparto = new Dialogo_Lista(this, true);

        reparto.RellenarTabla(PT.dlmPelis(Integer.parseInt(txtPeliId.getText())));
        reparto.SetPeli(txtPeliId.getText());
        reparto.botonesActivados(true);

        reparto.setVisible(true);
    }//GEN-LAST:event_btnRepartoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        if (checkearMinimosRequeridos()) {

            Language lng = ((LenguajeCombo) cmbPeliLenguaje.getSelectedItem()).getLanguage();
            String title = txtPeliTitulo.getText();
            byte rDuration = Byte.parseByte(txtPeliRTime.getText());
            BigDecimal rRate = BigDecimal.valueOf(Double.parseDouble(txtPeliRRate.getText()));
            BigDecimal rCost = BigDecimal.valueOf(Double.parseDouble(txtPeliRCost.getText()));
            Film filmCt;
            if (nuevoRegistro) {
                filmCt = new Film(lng, title, rDuration, rRate, rCost, new Date());

                rellenarPeli(filmCt);

                PT.addFilm(filmCt);
            } else {
                filmCt = PT.getPeli(PeliActual);

                filmCt.setLanguageByLanguageId(lng);
                filmCt.setTitle(title);
                filmCt.setRentalDuration(rDuration);
                filmCt.setRentalRate(rRate);
                filmCt.setReplacementCost(rCost);
                rellenarPeli(filmCt);

                PT.updFilm(PeliActual, filmCt);
            }
            habilitarEdicion(false);
            mostrarDatos(PeliActual);
        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String[] buttons = {"Si", "No"};
        int rc = JOptionPane.showOptionDialog(null, "Quitar la pelicula = [" + PeliActual + "]?",
                "Confirmation", JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons[1]);
        if (rc == 0) {
            PT.delFilm(PeliActual);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnte;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPrim;
    private javax.swing.JButton btnReparto;
    private javax.swing.JButton btnSigu;
    private javax.swing.JButton btnUlti;
    private javax.swing.JCheckBox chBehind;
    private javax.swing.JCheckBox chComentarios;
    private javax.swing.JCheckBox chDeleted;
    private javax.swing.JCheckBox chTrailers;
    private javax.swing.JComboBox cmbPeliLenguaje;
    private javax.swing.JComboBox cmbPeliRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtPeliActual;
    private javax.swing.JTextArea txtPeliDescripcion;
    private javax.swing.JTextField txtPeliDuracion;
    private javax.swing.JTextField txtPeliId;
    private javax.swing.JLabel txtPeliModificado;
    private javax.swing.JTextField txtPeliRCost;
    private javax.swing.JTextField txtPeliRRate;
    private javax.swing.JTextField txtPeliRTime;
    private javax.swing.JTextField txtPeliTitulo;
    private javax.swing.JLabel txtPeliTotal;
    // End of variables declaration//GEN-END:variables

    private void SetUi() {
        MT = new MyTools();
        PT = new PeliTools();
        PT.RellenarPelis();
        txtPeliDescripcion.setLineWrap(true);
        txtPeliDescripcion.setWrapStyleWord(true);
        PT.RellenarComboLenguaje(cmbPeliLenguaje);
        PT.RellenarComboRating(cmbPeliRating);

        if (PT.ContarPelis() > 0) {
            mostrarDatos(1);
        } else {
            MT.mostrarError("No hay pelis que mostrar");
            btnNuevoActionPerformed(null);
            btnCancel.setEnabled(false);
            PeliActual = 1;
        }

    }

    private void mostrarDatos(int reg) {

        String desc = "Sin descripcion";
        String duracion = "0";
        String rating = "";
        PeliActual = reg;
        Film peliTmp = PT.getPeli(reg);
        try {
            txtPeliActual.setText("" + PeliActual);
            txtPeliTotal.setText("" + PT.ContarPelis());
            txtPeliId.setText(peliTmp.getFilmId().toString());
            txtPeliTitulo.setText(peliTmp.getTitle());
            LenguajeCombo lngC = new LenguajeCombo(peliTmp.getLanguageByLanguageId().getLanguageId());
            cmbPeliLenguaje.setSelectedItem(lngC);
            txtPeliRTime.setText("" + peliTmp.getRentalDuration());
            txtPeliRRate.setText("" + peliTmp.getRentalRate());
            txtPeliRCost.setText("" + peliTmp.getReplacementCost());
            txtPeliModificado.setText(peliTmp.getLastUpdate().toString());
        } catch (Error ex) {
            MT.mostrarError("Error al cargar los datos minimos");
        }
        try {
            desc = peliTmp.getDescription();
            rellenarFeatures(peliTmp.getSpecialFeatures());
            duracion = peliTmp.getLength().toString();
            rating = peliTmp.getRating();
        } catch (Exception ex) {
            //MT.mostrarError("Error con los extras");
        }

        txtPeliDescripcion.setText(desc);
        txtPeliDuracion.setText(duracion);
        cmbPeliRating.setSelectedItem(rating);

        if (PeliActual == 1) {
            btnAnte.setEnabled(false);
            btnPrim.setEnabled(false);
        } else {
            btnAnte.setEnabled(true);
            btnPrim.setEnabled(true);
        }
        if (PeliActual == PT.ContarPelis()) {
            btnSigu.setEnabled(false);
            btnUlti.setEnabled(false);
        } else {
            btnSigu.setEnabled(true);
            btnUlti.setEnabled(true);
        }
        nuevoRegistro = false;

    }

    private void habilitarEdicion(boolean bl) {
        cmbPeliLenguaje.setEnabled(bl);
        txtPeliTitulo.setEnabled(bl);
        txtPeliDescripcion.setEnabled(bl);
        txtPeliDuracion.setEnabled(bl);
        chBehind.setEnabled(bl);
        chComentarios.setEnabled(bl);
        chDeleted.setEnabled(bl);
        chTrailers.setEnabled(bl);
        cmbPeliRating.setEnabled(bl);
        txtPeliRCost.setEnabled(bl);
        txtPeliRRate.setEnabled(bl);
        txtPeliRTime.setEnabled(bl);

        btnOk.setEnabled(bl);
        btnCancel.setEnabled(bl);

        btnReparto.setEnabled(!bl);
        btnNuevo.setEnabled(!bl);
        btnEditar.setEnabled(!bl);
        btnBorrar.setEnabled(!bl);
        btnPrim.setEnabled(!bl);
        btnAnte.setEnabled(!bl);
        btnSigu.setEnabled(!bl);
        btnUlti.setEnabled(!bl);
    }

    private boolean checkearMinimosRequeridos() {
        if (cmbPeliLenguaje.getSelectedIndex() < 0) {
            MT.mostrarError("Rellene el lenguaje");
            return false;
        }
        if (txtPeliTitulo.getText().equals("")) {
            MT.mostrarError("Rellene el título");
            return false;
        }
        if (txtPeliRCost.getText().equals("")) {
            MT.mostrarError("Rellene el coste de alquiler");
            return false;
        }
        if (txtPeliRRate.getText().equals("")) {
            MT.mostrarError("Rellene el porcentaje de alquiler");
            return false;
        }
        if (txtPeliRTime.getText().equals("")) {
            MT.mostrarError("Rellene el tiemp de alquiler");
            return false;
        }

        return true;
    }

    private void rellenarPeli(Film filmCt) {

        String descripcion = txtPeliDescripcion.getText();
        if (!descripcion.equals("")) {
            filmCt.setDescription(descripcion);
        }

        try {
            String duracion = txtPeliDuracion.getText();
            if (!duracion.equals("")) {
                filmCt.setLength(Short.parseShort(duracion));
            }
        } catch (Exception ex) {
            MT.mostrarError("Ingese la duracion de la peli correctamente");
        }

        if (cmbPeliRating.getSelectedIndex() >= 0) {
            String rating = cmbPeliRating.getSelectedItem().toString();
            filmCt.setRating(rating);
        }

        String features = "";
        if (chBehind.isSelected()) {
            features += "Behind the Scenes";
        }
        if (chComentarios.isSelected()) {
            if (!features.equals("")) {
                features += ",";
            }
            features += "Commentaries";
        }
        if (chDeleted.isSelected()) {
            if (!features.equals("")) {
                features += ",";
            }
            features += "Deleted Scenes";
        }
        if (chTrailers.isSelected()) {
            if (!features.equals("")) {
                features += ",";
            }
            features += "Trailers";
        }
        filmCt.setSpecialFeatures(features);
    }

    private void rellenarFeatures(String specialFeatures) {

        chBehind.setSelected(false);
        chComentarios.setSelected(false);
        chDeleted.setSelected(false);
        chTrailers.setSelected(false);
        try {
            String feaArray[] = specialFeatures.split(",");

            for (String ct : feaArray) {
                if (ct.equalsIgnoreCase("Trailers")) {
                    chTrailers.setSelected(true);
                }
                if (ct.equalsIgnoreCase("Commentaries")) {
                    chComentarios.setSelected(true);
                }
                if (ct.equalsIgnoreCase("Deleted Scenes")) {
                    chDeleted.setSelected(true);
                }
                if (ct.equalsIgnoreCase("Behind the Scenes")) {
                    chBehind.setSelected(true);
                }
            }
        } catch (NullPointerException ex) {

        }
    }
}
